# Services (Containers)
services:
  nginx:
      container_name: nginx
      image: nginx:inception
      env_file:
          - .env
      build:
          context: ./requirements/nginx
      depends_on:
          - wordpress
      networks:
          - inception
      volumes:
          - wordpress_data:/var/www/wordpress
          - adminer_data:/var/www/adminer
      ports:
          - 80:80
          - 443:443
      restart: unless-stopped

  mariadb:
      container_name: mariadb
      image: mariadb:inception
      env_file:
          - .env
      build:
          context: ./requirements/mariadb
          args:
              DEBIAN_VERSION: ${DEBIAN_VERSION}
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "--silent"]
          interval: 10s
          timeout: 5s
          retries: 5
      volumes:
          - wordpress_db:/var/lib/mysql
      networks:
          - inception
      expose:
          - 3306
      restart: unless-stopped

  wordpress:
      container_name: wordpress
      image: wordpress:inception
      env_file:
          - .env
      build:
          context: ./requirements/wordpress
      depends_on:
          mariadb:
              condition: service_healthy
      volumes:
          - wordpress_data:/var/www/wordpress
      networks:
          - inception
      expose:
          - 9000
      restart: unless-stopped

# Bonus Services (Containers)
  redis:
    build: ./requirements/bonus/redis-cache
    image: redis:inception
    container_name: redis
    restart: always
    networks:
      - inception
    expose:
      - "6379"

  ftp:
    container_name: ftp
    image: ftp:inception
    env_file:
      - .env
    build:
      context: ./requirements/bonus/ftp-server
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"

  static_site:
    container_name: static_site
    image: static-site:inception
    build: ./requirements/bonus/static-website
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - inception
    volumes:
      - static_html:/var/www/html

  adminer:
    container_name: adminer
    image: adminer:inception
    env_file:
        - .env
    build: 
        context: ./requirements/bonus/adminer
    restart: unless-stopped
    networks:
        - inception
    volumes:
        - adminer_data:/var/www/adminer
    ports:
        - "8082:80"

  cadvisor:
    container_name: cadvisor
    image: cadvisor:inception
    init: true
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

# Networks
networks:
  inception:
    driver: bridge

# Volumes
volumes:
  wordpress_db:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: ${HOME}/data/wordpress_db
  wordpress_data:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: ${HOME}/data/wordpress
  redis_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/redis"
  static_html:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/static_html"
  adminer_data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/adminer
