services:
  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"

  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    expose:
      - "9000"
    depends_on:
      - mariadb

  redis:
    build: ./srcs/requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
    expose:
      - "6379"

  ftp:
    container_name: ftp
    env_file:
      - .env
    build:
      context: ./srcs/requirements/bonus/ftp
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"

  static_site:
    container_name: static_site
    build: ./srcs/requirements/bonus/static_site
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - inception
    volumes:
      - static_html:/var/www/html

  adminer:
    build: ./srcs/requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8081:8080"
    restart: always
    networks:
      - inception

  quotes:
    build: ./srcs/requirements/bonus/API
    container_name: quotes
    ports:
      - "5000:5000"
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/wordpress"
  mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/mariadb"
  redis_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/redis"
  static_html:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/static_html"
